apiVersion: apps/v1
kind: Deployment
metadata:
  name: turtle-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: turtle
  template:
    metadata:
      labels:
        app: turtle
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
